### ISSUE TITLE
Parallelize sync per-module

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-distribution-container-image-sync#43]
Hi team, I was thinking on parallelize the image sync per-module.

What do you think?

@ralgozino

**Comment by ralgozino** [comment]
The only risk is overloading Drone with too much parallel bulds, but being that we are only building the changed images I think we could give it try. Maybe adding some parallel-runs limit?

**Comment by nutellinoit** [comment]
The pipeline is not on drone, but on GitHub actions

**Comment by nutellinoit** [comment]
Resolved with PR #45
